"""
Twilio Voice integration for VOCA project.
Handles SIP to WebRTC bridge and call management with real-time audio processing.
"""
import asyncio
import json
import logging
import time
import base64
import io
import os
import wave
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional, Callable, Dict, Any, List
from fastapi import FastAPI, Request, Response, HTTPException, WebSocket, WebSocketDisconnect
from fastapi.responses import PlainTextResponse, FileResponse, JSONResponse
import uvicorn
from twilio.rest import Client
from twilio.twiml.voice_response import VoiceResponse, Start, Stream, Play, Connect, ConversationRelay, Language
from twilio.twiml.messaging_response import MessagingResponse
import threading
import queue
import numpy as np
import websocket
import ssl
from urllib.parse import urlencode

from .twilio_config import get_twilio_config
from src.voca.orchestrator import VocaOrchestrator
from src.voca.config import Config


class TwilioVoiceHandler:
    """Handles Twilio voice calls and bridges them to VOCA orchestrator with real-time audio streaming."""
    
    def __init__(self, orchestrator: VocaOrchestrator):
        self.orchestrator = orchestrator
        config = get_twilio_config()
        self.client = Client(config.account_sid, config.auth_token)
        self.active_calls: Dict[str, Dict[str, Any]] = {}
        self.audio_queue = queue.Queue()
        self.logger = logging.getLogger(__name__)
        self._loop = None
        self.websocket_connections: Dict[str, websocket.WebSocket] = {}
        self.audio_buffers: Dict[str, list] = {}
        
        # Audio storage for testing/debugging
        self.audio_storage_dir = Path(Config.audio_storage_dir)
        self.audio_storage_dir.mkdir(parents=True, exist_ok=True)
        self.audio_writers: Dict[str, wave.Wave_write] = {}  # call_sid -> wave writer
        self.audio_chunk_counts: Dict[str, int] = {}  # Track chunk count per call
        
        # TTS audio cache directory
        self.tts_cache_dir = self.audio_storage_dir / "tts_cache"
        self.tts_cache_dir.mkdir(parents=True, exist_ok=True)
        self.webhook_host = None
        self.webhook_port = None
        
    def start_webhook_server(self, host='0.0.0.0', port=5000):
        """Start FastAPI server to handle Twilio webhooks with real-time audio streaming."""
        app = FastAPI(title="VOCA Twilio Webhook Server")
        
        # Store host and port for TTS URL generation
        self.webhook_host = host
        self.webhook_port = port
        
        # Store reference to self for route handlers
        handler = self
        
        @app.get('/tts/{text_hash}')
        async def serve_tts_audio(text_hash: str):
            """Serve TTS audio file generated by Deepgram."""
            try:
                audio_file = handler.tts_cache_dir / f"{text_hash}.wav"
                if audio_file.exists():
                    return FileResponse(
                        path=str(audio_file),
                        media_type="audio/wav",
                        headers={"Cache-Control": "public, max-age=31536000"}  # Cache for 1 year
                    )
                else:
                    raise HTTPException(status_code=404, detail="TTS audio file not found")
            except Exception as e:
                handler.logger.error(f"Error serving TTS audio: {e}")
                raise HTTPException(status_code=500, detail=str(e))
        
        @app.post('/webhook/voice')
        async def handle_incoming_call(request: Request):
            """Handle incoming Twilio voice calls using ConversationRelay with Deepgram."""
            form_data = await request.form()
            call_sid = form_data.get('CallSid')
            from_number = form_data.get('From')
            
            handler.logger.info(f"Incoming call from {from_number}, SID: {call_sid}")
            
            # Store call information
            handler.active_calls[call_sid] = {
                'from_number': from_number,
                'status': 'ringing',
                'start_time': time.time(),
                'audio_buffer': [],
                'unclear_count': 0,
                'last_speech_attempt': None,
                'name_attempt_count': 0
            }
            
            # Create TwiML response
            response = VoiceResponse()
            
            # Get WebSocket URL for ConversationRelay
            config = get_twilio_config()
            webhook_url = config.get_webhook_url()
            base_url = webhook_url.replace('/webhook/voice', '')
            
            # Convert to WebSocket URL (wss://)
            if base_url.startswith('http://'):
                wss_base_url = base_url.replace('http://', 'wss://')
            elif base_url.startswith('https://'):
                wss_base_url = base_url.replace('https://', 'wss://')
            elif not base_url.startswith('wss://'):
                wss_base_url = f"wss://{base_url.lstrip('/')}"
            else:
                wss_base_url = base_url
            
            websocket_url = f"{wss_base_url}/conversation/{call_sid}"
            
            # Set up ConversationRelay with Deepgram
            connect = Connect()
            conversationrelay = ConversationRelay(url=websocket_url)
            
            # Configure English (India) with Deepgram TTS and STT
            conversationrelay.language(
                code='en-IN',
                tts_provider='deepgram',
                voice='aura-2-odysseus-en',  # Deepgram TTS model
                transcription_provider='deepgram',
                speech_model='nova-3'  # Deepgram STT model
            )
            
            # Optionally add other languages if needed
            # conversationrelay.language(
            #     code='en-US',
            #     tts_provider='deepgram',
            #     voice='aura-2-ash-en',
            #     transcription_provider='deepgram',
            #     speech_model='nova-3'
            # )
            
            connect.append(conversationrelay)
            response.append(connect)
            
            handler.logger.info(f"[CONVERSATION_RELAY] Enabled ConversationRelay for call {call_sid}")
            handler.logger.info(f"[CONVERSATION_RELAY] WebSocket URL: {websocket_url}")
            handler.logger.info(f"[CONVERSATION_RELAY] Using Deepgram TTS (aura-2-odysseus-en) and STT (nova-3)")
            
            return Response(content=str(response), media_type='text/xml')
        
        @app.websocket('/conversation/{call_sid}')
        async def handle_conversation_relay(websocket: WebSocket, call_sid: str):
            """Handle ConversationRelay WebSocket connection from Twilio."""
            await websocket.accept()
            handler.logger.info(f"[CONVERSATION_RELAY] WebSocket connected for call {call_sid}")
            
            try:
                while True:
                    # Receive messages from Twilio ConversationRelay
                    data = await websocket.receive_json()
                    event_type = data.get('event', {}).get('type')
                    
                    handler.logger.debug(f"[CONVERSATION_RELAY] Received event: {event_type} for call {call_sid}")
                    
                    if event_type == 'start':
                        handler.logger.info(f"[CONVERSATION_RELAY] Conversation started for call {call_sid}")
                    elif event_type == 'media':
                        # Audio data from the call
                        handler.logger.debug(f"[CONVERSATION_RELAY] Received audio data for call {call_sid}")
                    elif event_type == 'text':
                        # Text transcription from Deepgram STT
                        transcription_text = data.get('event', {}).get('text', '')
                        if transcription_text:
                            handler.logger.info(f"[CONVERSATION_RELAY] Transcription: {transcription_text}")
                            
                            # Process through VOCA orchestrator
                            try:
                                ai_response = handler.orchestrator.generate_reply(
                                    transcription_text,
                                    conversation_id=call_sid,
                                    call_sid=call_sid,
                                )
                                handler.logger.info(f"[CONVERSATION_RELAY] AI Response: {ai_response}")
                                
                                # Send text response back to ConversationRelay (will be converted to speech by Deepgram TTS)
                                response_message = {
                                    'event': {
                                        'type': 'text',
                                        'text': ai_response
                                    }
                                }
                                await websocket.send_json(response_message)
                                handler.logger.info(f"[CONVERSATION_RELAY] Sent AI response to ConversationRelay")
                            except Exception as e:
                                handler.logger.error(f"[CONVERSATION_RELAY] Error processing transcription: {e}", exc_info=True)
                    elif event_type == 'stop':
                        handler.logger.info(f"[CONVERSATION_RELAY] Conversation stopped for call {call_sid}")
                        break
                    else:
                        handler.logger.debug(f"[CONVERSATION_RELAY] Unhandled event type: {event_type}")
                        
            except WebSocketDisconnect:
                handler.logger.info(f"[CONVERSATION_RELAY] WebSocket disconnected for call {call_sid}")
            except Exception as e:
                handler.logger.error(f"[CONVERSATION_RELAY] Error in WebSocket: {e}", exc_info=True)
        
        
        @app.post('/call/status')
        async def handle_call_status(request: Request):
            """Handle call status updates from Twilio."""
            form_data = await request.form()
            call_sid = form_data.get('CallSid')
            call_status = form_data.get('CallStatus')
            
            if call_sid in handler.active_calls:
                handler.active_calls[call_sid]['status'] = call_status
                handler.logger.info(f"Call {call_sid} status: {call_status}")
                
                if call_status in ['completed', 'failed', 'busy', 'no-answer']:
                    # Clean up call
                    handler.cleanup_call(call_sid)
            
            return PlainTextResponse("OK")
        
        @app.post('/outbound')
        async def handle_outbound_call(request: Request):
            """Handle outbound call TwiML using ConversationRelay with Deepgram."""
            form_data = await request.form()
            call_sid = form_data.get('CallSid')
            
            # Store call information
            handler.active_calls[call_sid] = {
                'to_number': 'outbound',
                'status': 'ringing',
                'start_time': time.time(),
                'audio_buffer': [],
                'unclear_count': 0,
                'last_speech_attempt': None,
                'name_attempt_count': 0
            }
            
            response = VoiceResponse()
            
            # Get WebSocket URL for ConversationRelay
            config = get_twilio_config()
            webhook_url = config.get_webhook_url()
            base_url = webhook_url.replace('/webhook/voice', '').replace('/outbound', '')
            
            # Convert to WebSocket URL (wss://)
            if base_url.startswith('http://'):
                wss_base_url = base_url.replace('http://', 'wss://')
            elif base_url.startswith('https://'):
                wss_base_url = base_url.replace('https://', 'wss://')
            elif not base_url.startswith('wss://'):
                wss_base_url = f"wss://{base_url.lstrip('/')}"
            else:
                wss_base_url = base_url
            
            websocket_url = f"{wss_base_url}/conversation/{call_sid}"
            
            # Set up ConversationRelay with Deepgram
            connect = Connect()
            conversationrelay = ConversationRelay(url=websocket_url)
            
            # Configure English (India) with Deepgram TTS and STT
            conversationrelay.language(
                code='en-IN',
                tts_provider='deepgram',
                voice='aura-2-odysseus-en',  # Deepgram TTS model
                transcription_provider='deepgram',
                speech_model='nova-3'  # Deepgram STT model
            )
            
            connect.append(conversationrelay)
            response.append(connect)
            
            handler.logger.info(f"[CONVERSATION_RELAY] Enabled ConversationRelay for outbound call {call_sid}")
            handler.logger.info(f"[CONVERSATION_RELAY] WebSocket URL: {websocket_url}")
            handler.logger.info(f"[CONVERSATION_RELAY] Using Deepgram TTS (aura-2-odysseus-en) and STT (nova-3)")
            
            return Response(content=str(response), media_type='text/xml')
        
        # Start server in a separate thread using uvicorn
        config = uvicorn.Config(app, host=host, port=port, log_level="info")
        server = uvicorn.Server(config)
        
        def run_server():
            import asyncio
            # Create new event loop for this thread
            loop = asyncio.new_event_loop()
            asyncio.set_event_loop(loop)
            loop.run_until_complete(server.serve())
        
        server_thread = threading.Thread(target=run_server, daemon=True)
        server_thread.start()
        self.logger.info(f"Twilio webhook server started on {host}:{port}")
        
        return app
    
    def make_outbound_call(self, to_number: str, message: str = None) -> str:
        """Make an outbound call using Twilio."""
        try:
            config = get_twilio_config()
            call = self.client.calls.create(
                to=to_number,
                from_=config.phone_number,
                url=f"{config.get_webhook_url().replace('/webhook/voice', '')}/outbound",
                method='POST'
            )
            
            call_sid = call.sid
            self.active_calls[call_sid] = {
                'to_number': to_number,
                'status': 'initiated',
                'start_time': time.time()
            }
            
            self.logger.info(f"Outbound call initiated to {to_number}, SID: {call_sid}")
            return call_sid
            
        except Exception as e:
            self.logger.error(f"Failed to make outbound call: {e}")
            return None
    
    def hangup_call(self, call_sid: str) -> bool:
        """Hang up an active call."""
        try:
            if call_sid in self.active_calls:
                call = self.client.calls(call_sid).update(status='completed')
                del self.active_calls[call_sid]
                self.logger.info(f"Call {call_sid} hung up")
                return True
            return False
        except Exception as e:
            self.logger.error(f"Failed to hang up call {call_sid}: {e}")
            return False
    
    def get_active_calls(self) -> Dict[str, Dict[str, Any]]:
        """Get information about active calls."""
        return self.active_calls.copy()
    
    def _save_audio_chunk(self, call_sid: str, audio_array: np.ndarray, sample_rate: int = 8000):
        """Save audio chunk to WAV file for testing/debugging."""
        try:
            # Initialize wave writer if not exists
            if call_sid not in self.audio_writers:
                call_dir = self.audio_storage_dir / call_sid
                call_dir.mkdir(parents=True, exist_ok=True)
                audio_file = call_dir / f"audio_{call_sid}.wav"
                
                writer = wave.open(str(audio_file), 'wb')
                writer.setnchannels(1)  # Mono
                writer.setsampwidth(2)  # 16-bit = 2 bytes
                writer.setframerate(sample_rate)
                self.audio_writers[call_sid] = writer
                self.audio_chunk_counts[call_sid] = 0
                self.logger.info(f"[AUDIO_CAPTURE] Started saving audio to {audio_file}")
            
            # Write audio data
            writer = self.audio_writers[call_sid]
            audio_bytes = audio_array.tobytes()
            writer.writeframes(audio_bytes)
            self.audio_chunk_counts[call_sid] += 1
            
            # Log every 100 chunks to avoid spam
            if self.audio_chunk_counts[call_sid] % 100 == 0:
                self.logger.info(f"[AUDIO_CAPTURE] Call {call_sid}: Saved {self.audio_chunk_counts[call_sid]} chunks, "
                               f"latest chunk size: {len(audio_array)} samples ({len(audio_array)/sample_rate:.2f}s)")
            
        except Exception as e:
            self.logger.error(f"[AUDIO_CAPTURE] Error saving audio chunk: {e}", exc_info=True)
    
    def process_audio_stream(self, call_sid: str, audio_data: bytes):
        """Process incoming audio stream from Twilio."""
        if call_sid not in self.active_calls:
            return
        
        # Store audio data in buffer
        if call_sid not in self.audio_buffers:
            self.audio_buffers[call_sid] = []
        
        self.audio_buffers[call_sid].append(audio_data)
        
        # Convert audio data to numpy array (assuming 16-bit PCM, 8kHz)
        try:
            audio_array = np.frombuffer(audio_data, dtype=np.int16)
            
            # Save audio chunk BEFORE processing (for testing)
            self._save_audio_chunk(call_sid, audio_array, sample_rate=8000)
            
            # Process through VOCA orchestrator
            self.orchestrator.handle_audio_chunk(audio_array, call_sid=call_sid)
            
        except Exception as e:
            self.logger.error(f"Error processing audio for call {call_sid}: {e}")
    
    def cleanup_call(self, call_sid: str):
        """Clean up resources for a call."""
        # Close and finalize audio writer
        if call_sid in self.audio_writers:
            try:
                writer = self.audio_writers[call_sid]
                writer.close()
                chunk_count = self.audio_chunk_counts.get(call_sid, 0)
                self.logger.info(f"[AUDIO_CAPTURE] Closed audio file for call {call_sid} ({chunk_count} chunks saved)")
            except Exception as e:
                self.logger.error(f"[AUDIO_CAPTURE] Error closing audio writer: {e}")
            del self.audio_writers[call_sid]
        
        if call_sid in self.audio_chunk_counts:
            del self.audio_chunk_counts[call_sid]
        
        if call_sid in self.active_calls:
            del self.active_calls[call_sid]
        
        if call_sid in self.audio_buffers:
            del self.audio_buffers[call_sid]
        
        if call_sid in self.websocket_connections:
            try:
                self.websocket_connections[call_sid].close()
            except:
                pass
            del self.websocket_connections[call_sid]
        
        self.logger.info(f"Cleaned up resources for call {call_sid}")


class TwilioCallManager:
    """Manages Twilio calls and integrates with VOCA orchestrator for real-time voice AI."""
    
    def __init__(self, orchestrator: VocaOrchestrator):
        self.orchestrator = orchestrator
        self.voice_handler = TwilioVoiceHandler(orchestrator)
        self.logger = logging.getLogger(__name__)
        self._server_thread = None
    
    def start(self, host='0.0.0.0', port=5000):
        """Start the Twilio call manager with real-time AI processing."""
        self.logger.info("Starting Twilio Call Manager with VOCA AI...")
        
        # Ensure models are loaded
        try:
            self.orchestrator.ensure_models_loaded()
            self.logger.info("VOCA models loaded successfully")
        except Exception as e:
            self.logger.error(f"Failed to load VOCA models: {e}")
            raise
        
        # Start webhook server
        self.voice_handler.start_webhook_server(host, port)
        
        self.logger.info("Twilio Call Manager started successfully")
        self.logger.info(f"Webhook URL: http://{host}:{port}/webhook/voice")
        self.logger.info("Ready to receive calls with real-time AI processing!")
    
    def make_call(self, phone_number: str, message: str = None) -> Optional[str]:
        """Make an outbound call with AI assistant."""
        self.logger.info(f"Making outbound call to {phone_number}")
        return self.voice_handler.make_outbound_call(phone_number, message)
    
    def hangup_all_calls(self):
        """Hang up all active calls."""
        for call_sid in list(self.voice_handler.active_calls.keys()):
            self.voice_handler.hangup_call(call_sid)
        self.logger.info("All calls hung up")
    
    def get_call_status(self) -> Dict[str, Any]:
        """Get status of all calls."""
        return {
            'active_calls': len(self.voice_handler.active_calls),
            'calls': self.voice_handler.get_active_calls(),
            'models_ready': self.orchestrator.models_ready()
        }
    
    def fetch_call_history(
        self,
        limit: int = 50,
        start_time_after: Optional[datetime] = None,
        start_time_before: Optional[datetime] = None,
    ) -> Dict[str, List[Dict[str, Any]]]:
        """Fetch recent call records from Twilio and bucket them by status."""
        client = self.voice_handler.client

        def _to_iso(dt: Optional[datetime]) -> Optional[str]:
            if not dt:
                return None
            if dt.tzinfo is None:
                dt = dt.replace(tzinfo=timezone.utc)
            return dt.astimezone(timezone.utc).isoformat()

        def _format_duration(duration_seconds: Optional[int]) -> Optional[str]:
            if duration_seconds is None:
                return None
            hours, remainder = divmod(duration_seconds, 3600)
            minutes, seconds = divmod(remainder, 60)
            return f"{hours:02}:{minutes:02}:{seconds:02}"

        declined_statuses = {"busy", "failed", "no-answer", "canceled"}
        ongoing_statuses = {"queued", "ringing", "in-progress"}
        completed_statuses = {"completed"}

        summary: Dict[str, List[Dict[str, Any]]] = {
            "ongoing": [],
            "declined": [],
            "completed": [],
            "others": [],
        }

        seen: Dict[str, Dict[str, Any]] = {}

        def _upsert_call(call_obj):
            if call_obj.sid in seen:
                return
            duration_seconds: Optional[int] = None
            if call_obj.duration is not None:
                try:
                    duration_seconds = int(call_obj.duration)
                except (TypeError, ValueError):
                    duration_seconds = None

            record = {
                "call_sid": call_obj.sid,
                "status": call_obj.status,
                "from_number": getattr(call_obj, "from_", None),
                "to_number": getattr(call_obj, "to", None),
                "direction": getattr(call_obj, "direction", None),
                "start_time": _to_iso(getattr(call_obj, "start_time", None)),
                "end_time": _to_iso(getattr(call_obj, "end_time", None)),
                "duration_seconds": duration_seconds,
                "duration_human": _format_duration(duration_seconds) if duration_seconds is not None else None,
            }
            seen[call_obj.sid] = record

        # Fetch specific status buckets first for accuracy with in-progress calls.
        status_fetch_plan = [
            ("ongoing", list(ongoing_statuses)),
            ("declined", list(declined_statuses)),
            ("completed", list(completed_statuses)),
        ]

        for _, status_list in status_fetch_plan:
            for status in status_list:
                try:
                    calls_by_status = client.calls.list(
                        status=status,
                        limit=limit,
                        start_time_after=start_time_after,
                        start_time_before=start_time_before,
                    )
                except Exception:
                    continue
                for call_obj in calls_by_status:
                    _upsert_call(call_obj)

        # Fallback: fetch recent calls without status filter to pick up any remaining records.
        try:
            fallback_calls = client.calls.list(
                limit=limit,
                start_time_after=start_time_after,
                start_time_before=start_time_before,
            )
            for call_obj in fallback_calls:
                _upsert_call(call_obj)
        except Exception:
            pass

        for record in seen.values():
            status_value = record["status"]
            if status_value in ongoing_statuses:
                summary["ongoing"].append(record)
            elif status_value in declined_statuses:
                summary["declined"].append(record)
            elif status_value in completed_statuses:
                summary["completed"].append(record)
            else:
                summary["others"].append(record)

        # Merge locally tracked active calls to surface immediate state changes before Twilio propagates them.
        timestamp_now = datetime.now(timezone.utc).isoformat()
        for call_sid, call_info in self.voice_handler.get_active_calls().items():
            if call_sid in seen:
                continue
            status = call_info.get("status", "initiated")
            start_ts = call_info.get("start_time")
            if isinstance(start_ts, (int, float)):
                start_iso = datetime.fromtimestamp(start_ts, tz=timezone.utc).isoformat()
            else:
                start_iso = _to_iso(start_ts) if isinstance(start_ts, datetime) else None
            local_record = {
                "call_sid": call_sid,
                "status": status,
                "from_number": call_info.get("from_number"),
                "to_number": call_info.get("to_number"),
                "direction": call_info.get("direction", "outbound-api"),
                "start_time": start_iso or timestamp_now,
                "end_time": None,
                "duration_seconds": int(time.time() - start_ts) if isinstance(start_ts, (int, float)) else None,
                "duration_human": None,
            }
            if status in ongoing_statuses or status == "initiated":
                summary["ongoing"].append(local_record)
            elif status in declined_statuses:
                summary["declined"].append(local_record)
            elif status in completed_statuses:
                summary["completed"].append(local_record)
            else:
                summary["others"].append(local_record)

        return summary
    
    def stop(self):
        """Stop the call manager and clean up resources."""
        self.hangup_all_calls()
        self.logger.info("Twilio Call Manager stopped")